---
- name: server logs
  shell: journalctl -u openvpn@server --since "5 minutes ago" --no-pager
  become: yes
  changed_when: false
  register: shell

- name: status logs
  shell: cat /var/log/openvpn/openvpn-status.log
  become: yes
  changed_when: false
  register: shell