---
- name: copy installer
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: 0755
  changed_when: false

- name: install pi locally
  shell: bash /tmp/install.sh
  changed_when: false

- name: copy models.json
  copy:
    src: models.json
    dest: $HOME/.pi/agent/models.json
    mode: 0755
  changed_when: false

- name: update npm
  shell: npm update
  changed_when: false
