---
- name: copy installer
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: 0755
  changed_when: false

- name: install pi locally
  shell: bash /tmp/install.sh
  changed_when: false

- name: clone https://github.com/TheShellLand/pi-agent.git
  shell: git clone https://github.com/TheShellLand/pi-agent.git
  changed_when: false

- name: copy models.json
  shell: cp -v pi-agent/models.json $HOME/.pi/agent/models.json
  changed_when: false

- name: update npm
  shell: npm update
  changed_when: false
