---
- shell: apt update && apt --fix-broken -y install
  become: yes
  changed_when: false

- name: "{{ansible_facts.architecture}}"
  include_tasks: "{{ansible_facts.architecture}}.yml"

- include_role:
    name: apt-installer
  vars:
    package: fonts-liberation

- shell: apt update && apt --fix-broken -y install
  become: yes
  changed_when: false
