---
- name: get default interface
  shell: ip route | grep -m 1 default | awk '{print $5}'
  register: shell
  failed_when: shell.stderr | default('', true) | length > 0
  changed_when: false

- set_fact:
    interface: "{{shell.stdout}}"

- name: configure iptables v4
  shell: |
    touch /etc/network/iptables.up.rules
    iptables -C INPUT -p udp --dport 22 -j ACCEPT 2>/dev/null || \
    iptables -A INPUT -p udp --dport 22 -j ACCEPT
  become: yes
  register: shell
  failed_when: shell.stderr | default('', true) | length > 0
  changed_when: false

- name: configure iptables v6
  shell: |
    touch /etc/network/ip6tables.up.rules
    ip6tables -C INPUT -p udp --dport 22 -j ACCEPT 2>/dev/null || \
    ip6tables -A INPUT -p udp --dport 22 -j ACCEPT
  become: yes
  register: shell
  failed_when: shell.stderr | default('', true) | length > 0
  changed_when: false

- include_role: name=iptables-save
- include_role: name=iptables-show-rules
