---
- set_fact:
    EXISTS: false

- name: Check if directory exists
  ansible.builtin.stat:
    path: /etc/openvpn/easy-rsa
  register: dir_info

- name: Task to run only if directory exists
  set_fact:
    EXISTS: true
  when: dir_info.stat.isdir is defined and dir_info.stat.isdir

- name: generate client keys
  shell: |
    cd /etc/openvpn/easy-rsa
    ./easyrsa --batch gen-req "{{ CLIENT_NAME }}" nopass
    ./easyrsa --batch sign-req client "{{ CLIENT_NAME }}"
  become: yes
  changed_when: false

- name: "create client ovpn {{ CLIENT_NAME }}"
  shell: |
    cd /etc/openvpn/easy-rsa

    # ca.crt, client1.crt, client1.key, ta.key required

    # Configuration
    CLIENT_NAME="{{ CLIENT_NAME }}"
    OUTPUT_DIR="./clients"
    KEY_DIR="./pki"
    SERVER_IP="{{ SERVER_IP }}"
    PORT="{{ SERVER_PORT }}"
    PROTO="{{ SERVER_PROTO }}"

    mkdir -p "$OUTPUT_DIR"

    cat > "$OUTPUT_DIR/$CLIENT_NAME.ovpn" << EOF
    client
    dev tun
    proto $PROTO
    remote $SERVER_IP $PORT
    resolv-retry infinite
    nobind
    persist-key
    persist-tun
    remote-cert-tls server
    cipher AES-256-CBC
    verb 3
    compress lzo

    <ca>
    $(cat "$KEY_DIR/ca.crt")
    </ca>

    <cert>
    $(awk '/BEGIN/,/END/' "$KEY_DIR/issued/$CLIENT_NAME.crt")
    </cert>

    <key>
    $(cat "$KEY_DIR/private/$CLIENT_NAME.key")
    </key>

    <tls-auth>
    $(cat "ta.key")
    </tls-auth>
    key-direction 1
    EOF

    echo "Client config generated: $OUTPUT_DIR/$CLIENT_NAME.ovpn"
  become: yes
  changed_when: false

- name: copy client ovpn
  fetch:
    src: "/etc/openvpn/easy-rsa/clients/{{ CLIENT_NAME }}.ovpn"
    dest: "."
  become: yes
  changed_when: false
