---
- name: "Allow user to run any commands - {{ ansible_facts['user_id'] }}"
  community.general.sudoers:
    name: "{{ ansible_facts['user_id'] }}"
    state: present
    user: "{{ ansible_facts['user_id'] }}"
    runas: root
    commands: ALL
  become: yes
  changed_when: false