---
- name: get default interface
  shell: ip route | grep -m 1 default | awk '{print $5}'
  register: shell
  failed_when: 
    - shell.stderr is defined
    - shell.stderr is not none
    - shell.stderr | length > 0
  changed_when: false

- set_fact:
    interface: "{{shell.stdout}}"
