---
- name: show v4 rules
  shell: cat /etc/iptables/rules.v4
  become: yes
  changed_when: false
  register: v4

- name: show v6 rules
  shell: cat /etc/iptables/rules.v6
  become: yes
  changed_when: false
  register: v6

- name: ipv6
  debug:
    var: v6.stdout

- name: ipv4
  debug:
    var: v4.stdout