---
- hosts: openvpn
  roles:
    - openvpn
    - iptables-flush
    - iptables-defaults
    - iptables-enable-forwarding
    - iptables-rule-accept-ssh
    - iptables-rule-accept-openvpn
    - iptables-rule-drop-all
    - iptables-reset-counters
    - iptables-show-rules