---
- hosts: all
  roles:
    - readyup
  vars:
    GUI: false
    CHROME: true
    BRAVE: false

    AGENT: true

    KEEPASS: true
    CODING: true
    PHOTOGRAPHY: true
    MEDIA: false
    GAMING: false
    DESKTOP: true

    RASPBERRYPI: false
    SERVER: false
    SERVER_LITE: false
    SERVER_SUPER_LITE: false

    WORK: false
    WORK_LITE: false

    TIGERVNC_PASSWORD:
